import { prisma } from "@/lib/prisma";
import { notFound } from "next/navigation";
import PrintButton from "@/components/PrintButton";

export default async function ContributionReceiptPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  const [contribution, settings] = await Promise.all([
    prisma.contribution.findUnique({
      where: { id: BigInt(id) },
      include: {
        member: {
          include: {
            user: true,
            branch: true,
          },
        },
        category: true,
      },
    }),
    prisma.systemSetting.findMany(),
  ]);

  if (!contribution) notFound();

  const getSetting = (key: string) =>
    settings.find((s) => s.settingKey === key)?.settingValue || "";

  return (
    <main className="mx-auto max-w-4xl bg-white p-8 text-slate-900">
      <div className="mb-6 flex items-center justify-between border-b pb-6">
        <div className="flex items-center gap-4">
          <div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-gradient-to-br from-blue-600 via-purple-600 to-red-600 text-4xl font-black text-white shadow-xl">
            Y
          </div>
          <div>
            <h1 className="text-3xl font-bold">
              {getSetting("platform_name") || "Youth Empowerment Platform"}
            </h1>
            <p className="text-slate-500">
              P.O. Box: {getSetting("po_box") || "-"} • KRA PIN: {getSetting("kra_pin") || "-"}
            </p>
            <p className="text-slate-500">
              Phone: {getSetting("company_phone") || "-"} • Email: {getSetting("company_email") || "-"}
            </p>
            <p className="text-slate-500">
              Bank: {getSetting("bank_name") || "-"} • Acc: {getSetting("bank_account_number") || "-"}
            </p>
          </div>
        </div>

        <PrintButton />
      </div>

      <div className="mb-8 rounded-2xl bg-gradient-to-r from-blue-700 via-purple-700 to-red-600 p-6 text-white">
        <h2 className="text-2xl font-bold">Contribution Receipt</h2>
        <p className="mt-1 text-white/90">Official printable receipt</p>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <div className="rounded-2xl border p-5">
          <h3 className="text-xl font-semibold">Member Details</h3>
          <div className="mt-4 space-y-2 text-sm">
            <p><span className="font-semibold">Name:</span> {contribution.member.user.fullName}</p>
            <p><span className="font-semibold">Phone:</span> {contribution.member.user.phone}</p>
            <p><span className="font-semibold">Email:</span> {contribution.member.user.email ?? "-"}</p>
            <p><span className="font-semibold">Branch:</span> {contribution.member.branch?.name ?? "-"}</p>
            <p><span className="font-semibold">Member No:</span> {contribution.member.memberNumber}</p>
          </div>
        </div>

        <div className="rounded-2xl border p-5">
          <h3 className="text-xl font-semibold">Receipt Details</h3>
          <div className="mt-4 space-y-2 text-sm">
            <p><span className="font-semibold">Category:</span> {contribution.category.name}</p>
            <p><span className="font-semibold">Amount:</span> KES {Number(contribution.amount).toLocaleString()}</p>
            <p><span className="font-semibold">Method:</span> {contribution.paymentMethod}</p>
            <p><span className="font-semibold">Reference:</span> {contribution.transactionReference ?? "-"}</p>
            <p><span className="font-semibold">Status:</span> {contribution.status}</p>
            <p><span className="font-semibold">Date:</span> {new Date(contribution.paymentDate).toLocaleString()}</p>
          </div>
        </div>
      </div>

      <div className="mt-8 rounded-2xl border p-5">
        <h3 className="text-xl font-semibold">Notes</h3>
        <p className="mt-3 text-sm text-slate-600">
          {contribution.notes || "Thank you for your contribution."}
        </p>
      </div>

      <div className="mt-10 border-t pt-6 text-sm text-slate-500">
        Generated by Youth Empowerment Platform.
      </div>
    </main>
  );
}