export const runtime = "nodejs";

import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import {
  PDFDocument,
  StandardFonts,
  rgb,
} from "pdf-lib";
import fs from "fs";
import path from "path";

export async function GET() {
  try {
    // =========================
    // 📊 FETCH DATA
    // =========================
    let totalMembers = 0;
    let totalContributions = 0;
    let totalProjects = 0;
    let totalAmount = 0;
    let transactions: any[] = [];

    try {
      totalMembers = await prisma.memberProfile.count();
      totalContributions = await prisma.contribution.count();
      totalProjects = await prisma.project.count();

      const sum = await prisma.contribution.aggregate({
        _sum: { amount: true },
      });

      totalAmount = Number(sum._sum.amount || 0);

      transactions = await prisma.contribution.findMany({
        take: 30, // multi-page
        orderBy: { createdAt: "desc" },
        include: {
          member: {
            include: { user: true },
          },
        },
      });
    } catch (e) {
      console.log("DB error:", e);
    }

    // =========================
    // 📄 CREATE PDF
    // =========================
    const pdfDoc = await PDFDocument.create();

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // =========================
    // 🖼 LOAD LOGO
    // =========================
    const logoPath = path.join(process.cwd(), "public/logo.png");
    const logoBytes = fs.readFileSync(logoPath);
    const logoImage = await pdfDoc.embedPng(logoBytes);

    // =========================
    // 🧾 PAGE 1 (SUMMARY)
    // =========================
    let page = pdfDoc.addPage([600, 800]);
    let { width, height } = page.getSize();

    // 🔵 HEADER
    page.drawRectangle({
      x: 0,
      y: height - 100,
      width,
      height: 100,
      color: rgb(0, 0.3, 0.8),
    });

    // 🖼 BIG LOGO
    page.drawImage(logoImage, {
      x: 30,
      y: height - 90,
      width: 70,
      height: 70,
    });

    // TITLE
    page.drawText("YEP PLATFORM REPORT", {
      x: 120,
      y: height - 55,
      size: 18,
      font: bold,
      color: rgb(1, 1, 1),
    });

    // 📅 DATE
    page.drawText(new Date().toLocaleString(), {
      x: 50,
      y: height - 120,
      size: 10,
      font,
    });

    // 🔴 SUMMARY TITLE
    page.drawText("System Summary", {
      x: 50,
      y: height - 150,
      size: 14,
      font: bold,
      color: rgb(1, 0, 0),
    });

    let y = height - 180;

    const summary = [
      ["Members", totalMembers],
      ["Contributions", totalContributions],
      ["Projects", totalProjects],
    ];

    summary.forEach((row) => {
      page.drawText(`${row[0]}: ${row[1]}`, {
        x: 60,
        y,
        size: 12,
        font,
      });
      y -= 20;
    });

    // 🟢 FINANCIAL
    y -= 20;

    page.drawText("Financial Summary", {
      x: 50,
      y,
      size: 14,
      font: bold,
      color: rgb(0, 0.6, 0),
    });

    y -= 25;

    page.drawText(
      `Total Contributions: KES ${totalAmount.toLocaleString()}`,
      {
        x: 60,
        y,
        size: 12,
        font,
      }
    );

    // =========================
    // 🌊 WATERMARK (LOGO BACKGROUND)
    // =========================
    page.drawImage(logoImage, {
      x: 150,
      y: 200,
      width: 300,
      height: 300,
      opacity: 0.08,
    });

    // FOOTER
    page.drawText("Generated by YEP System", {
      x: 200,
      y: 40,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    // =========================
    // 📄 PAGE 2+ (TRANSACTIONS)
    // =========================
    page = pdfDoc.addPage([600, 800]);
    ({ width, height } = page.getSize());

    // HEADER AGAIN
    page.drawRectangle({
      x: 0,
      y: height - 80,
      width,
      height: 80,
      color: rgb(0, 0.3, 0.8),
    });

    page.drawText("Transactions Report", {
      x: 200,
      y: height - 50,
      size: 16,
      font: bold,
      color: rgb(1, 1, 1),
    });

    let startY = height - 120;

    // TABLE HEADER
    page.drawRectangle({
      x: 50,
      y: startY,
      width: 500,
      height: 20,
      color: rgb(0, 0.3, 0.8),
    });

    page.drawText("Name", { x: 60, y: startY + 5, size: 10, font: bold, color: rgb(1,1,1) });
    page.drawText("Amount", { x: 250, y: startY + 5, size: 10, font: bold, color: rgb(1,1,1) });
    page.drawText("Date", { x: 400, y: startY + 5, size: 10, font: bold, color: rgb(1,1,1) });

    let rowY = startY - 20;

    transactions.forEach((t, i) => {
      // NEW PAGE IF FULL
      if (rowY < 50) {
        page = pdfDoc.addPage([600, 800]);
        rowY = height - 80;
      }

      page.drawRectangle({
        x: 50,
        y: rowY,
        width: 500,
        height: 20,
        color: i % 2 === 0 ? rgb(0.95, 0.95, 0.95) : rgb(1, 1, 1),
      });

      page.drawText(
        t.member?.user?.fullName || "N/A",
        { x: 60, y: rowY + 5, size: 10, font }
      );

      page.drawText(
        `KES ${Number(t.amount).toLocaleString()}`,
        { x: 250, y: rowY + 5, size: 10, font }
      );

      page.drawText(
        new Date(t.createdAt).toLocaleDateString(),
        { x: 400, y: rowY + 5, size: 10, font }
      );

      rowY -= 20;
    });

    // =========================
    // 📦 FINAL OUTPUT
    // =========================
    const pdfBytes = await pdfDoc.save();
    const buffer = Buffer.from(pdfBytes);

    return new NextResponse(buffer, {
      headers: {
        "Content-Type": "application/pdf",
      },
    });

  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "Error generating PDF" },
      { status: 500 }
    );
  }
}