import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { prisma } from "@/lib/prisma";
import fs from "fs";
import path from "path";

export async function GET() {
  try {
    // 📊 DATA
    const [
      totalMembers,
      totalContributions,
      totalProjects,
      totalWelfareRequests,
      totalTrainings,
      totalReferrals,
      totalCommissions,
    ] = await Promise.all([
      prisma.memberProfile.count(),
      prisma.contribution.count(),
      prisma.project.count(),
      prisma.welfareRequest.count(),
      prisma.training.count(),
      prisma.referral.count(),
      prisma.commission.count(),
    ]);

    const contributionSum = await prisma.contribution.aggregate({
      _sum: { amount: true },
    });

    const projectBudgetSum = await prisma.project.aggregate({
      _sum: { budgetAmount: true },
    });

    const welfareAmountSum = await prisma.welfareRequest.aggregate({
      _sum: { amountRequested: true },
    });

    // 📄 PDF START
    const doc = new PDFDocument({ margin: 40 });

    let buffers: any[] = [];
    doc.on("data", buffers.push.bind(buffers));

    // 📌 LOGO (put your logo inside /public/logo.png)
    const logoPath = path.join(process.cwd(), "public/logo.png");
    if (fs.existsSync(logoPath)) {
      doc.image(logoPath, 40, 30, { width: 60 });
    }

    // 🎨 HEADER
    doc
      .fillColor("#2563eb")
      .fontSize(22)
      .text("YEP PLATFORM REPORT", 120, 40);

    doc
      .fillColor("black")
      .fontSize(10)
      .text(`Generated: ${new Date().toLocaleString()}`, 120, 70);

    doc.moveDown(3);

    // 🧾 SECTION: SUMMARY
    doc
      .fillColor("#1e40af")
      .fontSize(16)
      .text("System Summary", { underline: true });

    doc.moveDown();

    doc.fillColor("black").fontSize(12);

    doc.text(`Members: ${totalMembers}`);
    doc.text(`Contributions: ${totalContributions}`);
    doc.text(`Projects: ${totalProjects}`);
    doc.text(`Welfare Requests: ${totalWelfareRequests}`);

    doc.moveDown();

    // 💰 FINANCIAL
    doc
      .fillColor("#16a34a")
      .fontSize(16)
      .text("Financial Summary", { underline: true });

    doc.moveDown();

    doc.fillColor("black").fontSize(12);

    doc.text(
      `Total Contributions: KES ${Number(
        contributionSum._sum.amount || 0
      ).toLocaleString()}`
    );

    doc.text(
      `Project Budget: KES ${Number(
        projectBudgetSum._sum.budgetAmount || 0
      ).toLocaleString()}`
    );

    doc.text(
      `Welfare Support: KES ${Number(
        welfareAmountSum._sum.amountRequested || 0
      ).toLocaleString()}`
    );

    doc.moveDown();

    // 📈 GROWTH
    doc
      .fillColor("#9333ea")
      .fontSize(16)
      .text("Growth Metrics", { underline: true });

    doc.moveDown();

    doc.fillColor("black").fontSize(12);

    doc.text(`Trainings: ${totalTrainings}`);
    doc.text(`Referrals: ${totalReferrals}`);
    doc.text(`Commissions: ${totalCommissions}`);

    doc.moveDown(2);

    // 📌 FOOTER
    doc
      .fillColor("#6b7280")
      .fontSize(10)
      .text("Generated by YEP System", { align: "center" });

    doc.end();

    const pdfBuffer = await new Promise<Buffer>((resolve) => {
      doc.on("end", () => {
        resolve(Buffer.concat(buffers));
      });
    });

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": "inline; filename=YEP_Report.pdf",
      },
    });
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "Error generating PDF" },
      { status: 500 }
    );
  }
}