export const runtime = "nodejs";

import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function GET() {
  try {
    // 📊 DATA
    let totalMembers = 0;

    try {
      totalMembers = await prisma.memberProfile.count();
    } catch (e) {
      console.log("DB error:", e);
    }

    // 📄 CREATE PDF
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([600, 800]);

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

    const { width, height } = page.getSize();

    // 🎨 HEADER
    page.drawRectangle({
      x: 0,
      y: height - 80,
      width: width,
      height: 80,
      color: rgb(0.15, 0.39, 0.92),
    });

    page.drawText("YEP PLATFORM REPORT", {
      x: 50,
      y: height - 50,
      size: 18,
      font,
      color: rgb(1, 1, 1),
    });

    // 📅 DATE
    page.drawText(new Date().toLocaleString(), {
      x: 50,
      y: height - 100,
      size: 10,
      font,
    });

    // 📊 CONTENT
    page.drawText("System Summary", {
      x: 50,
      y: height - 140,
      size: 14,
      font,
    });

    page.drawText(`Total Members: ${totalMembers}`, {
      x: 50,
      y: height - 170,
      size: 12,
      font,
    });

    // 📌 FOOTER
    page.drawText("Generated by YEP System", {
      x: 200,
      y: 30,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(pdfBytes, {
      headers: {
        "Content-Type": "application/pdf",
      },
    });
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "Error generating PDF" },
      { status: 500 }
    );
  }
}